import Head from "next/head"
import { Formik, Field, Form } from "formik"
import { useState } from "react"
import * as yup from "yup"

import "@primer/css/base/index.scss"
import "@primer/css/index.scss"
import "@primer/css/Utilities/index.scss"

const schema = yup.object().shape({
  size: yup.number().required().moreThan(9).lessThan(121),
  length: yup.number().required().moreThan(4).lessThan(14),
  color: yup.number().required().moreThan(-1).lessThan(361),
})

export default function Home() {
  const [wormShit, setWormShit] = useState({
    size: 50,
    length: 6,
    color: 200,
  })

  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="wrapper border">
        <h1 className="text-bold">
          Wiggly Worm<sup>v2</sup>
        </h1>
        <div>
          <h2 className="text-underline text-normal">
            What is this monstrosity?
          </h2>
          <p style={{ maxWidth: "25rem" }}>
            This <strong>thing </strong>
            is basically the second version of a stupid project I made like a
            year ago for fun. Yes, this is literally it. Uhh... Have fun, I
            guess?
          </p>
        </div>
        <div>
          <h2 className="text-underline text-normal">Settings</h2>
          <Formik
            initialValues={{
              size: 50,
              length: 6,
              color: 200,
            }}
            validationSchema={schema}
            onSubmit={(values) => {
              setWormShit({
                size: values.size,
                length: values.length,
                color: values.color,
              })
            }}
          >
            <Form>
              <div className="mb-2">
                <label htmlFor="size">
                  Worm Block Size{" "}
                  <span className="color-fg-danger small text-normal">
                    min: 10 max: 120
                  </span>
                </label>
                <Field
                  id="size"
                  name="size"
                  placeholder="20"
                  type="number"
                  className="form-control"
                />
              </div>
              <div className="mb-2">
                <label htmlFor="length">
                  Worm Length{" "}
                  <span className="color-fg-danger small text-normal">
                    min: 6 max: 20
                  </span>
                </label>
                <Field
                  id="length"
                  name="length"
                  placeholder="6"
                  type="number"
                  className="form-control"
                />
              </div>
              <div className="mb-2">
                <label htmlFor="color">
                  Worm Color in Degrees{" "}
                  <span className="color-fg-danger small text-normal">
                    min: 0 max: 360
                  </span>
                </label>
                <Field
                  id="color"
                  name="color"
                  placeholder="200"
                  type="number"
                  className="form-control"
                />
              </div>
              <button type="submit" className="btn btn-primary mr-2">
                Apply Changes
              </button>
            </Form>
          </Formik>
        </div>
      </section>
      <main
        className="board"
        style={{ backgroundColor: `hsl(${wormShit.color}, 50%, 90%)` }}
      >
        <div className="worm">
          {[...Array(wormShit.length)].map((i, index) => {
            return (
              <div
                className="worm__block"
                style={{
                  animationDelay: `${index * 200}ms`,
                  width: `${wormShit.size}px`,
                  height: `${wormShit.size}px`,
                  backgroundColor: `hsl(${wormShit.color}, 60%, ${
                    index * 5 + 40
                  }%)`,
                  borderRadius: "10px",
                }}
              ></div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
